-- ============================================================
-- GTD Data Warehouse - Post-ETL Constraints and Indexes
-- Run after FACT_GTD_EVENT is loaded
-- ============================================================

-- Primary Keys (rely)
ALTER TABLE DIM_LUGAR ADD CONSTRAINT DIM_LUGAR_PK PRIMARY KEY(LUGAR_SK) RELY;
ALTER TABLE DIM_DETALLE ADD CONSTRAINT DIM_DETALLE_PK PRIMARY KEY(DETALLE_SK) RELY;
ALTER TABLE DIM_ESPEC_LUGAR ADD CONSTRAINT DIM_ESPEC_LUGAR_PK PRIMARY KEY(SPEC_LUGAR_SK) RELY;
ALTER TABLE DIM_DETALLES_A ADD CONSTRAINT DIM_DETALLES_A_PK PRIMARY KEY(DETALLES_A_SK) RELY;
ALTER TABLE DIM_ARMA ADD CONSTRAINT DIM_ARMA_PK PRIMARY KEY(ARMAS_SK) RELY;
ALTER TABLE DIM_ATAQUE ADD CONSTRAINT DIM_ATAQUE_PK PRIMARY KEY(ATAQUE_SK) RELY;
ALTER TABLE DIM_PERPETRADORES ADD CONSTRAINT DIM_PERPETRADORES_PK PRIMARY KEY(PERP_SK) RELY;
ALTER TABLE DIM_MCR ADD CONSTRAINT DIM_MCR_PK PRIMARY KEY(MCR_SK) RELY;
ALTER TABLE DIM_OBJETIVOS ADD CONSTRAINT DIM_OBJETIVOS_PK PRIMARY KEY(OBJETIVO_SK) RELY;
ALTER TABLE DIM_IMPACTO ADD CONSTRAINT DIM_IMPACTO_PK PRIMARY KEY(IMPACTO_SK) RELY;
ALTER TABLE DIM_GPERP ADD CONSTRAINT DIM_GPERP_PK PRIMARY KEY(GRUPO_SK) RELY;

-- Foreign Keys (rely disable novalidate)
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_TIEMPO FOREIGN KEY(FK_TIEMPO_INI) REFERENCES DIM_TIEMPO(TIEMPO_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_LUGAR FOREIGN KEY(FK_LUGAR) REFERENCES DIM_LUGAR(LUGAR_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_ESPEC_LUGAR FOREIGN KEY(FK_ESPEC_LUGAR) REFERENCES DIM_ESPEC_LUGAR(SPEC_LUGAR_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_DETALLE FOREIGN KEY(FK_DETALLE) REFERENCES DIM_DETALLE(DETALLE_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_DETALLES_A FOREIGN KEY(FK_DETALLES_A) REFERENCES DIM_DETALLES_A(DETALLES_A_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_ARMA1 FOREIGN KEY(FK_ARMA1) REFERENCES DIM_ARMA(ARMAS_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_ARMA2 FOREIGN KEY(FK_ARMA2) REFERENCES DIM_ARMA(ARMAS_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_ARMA3 FOREIGN KEY(FK_ARMA3) REFERENCES DIM_ARMA(ARMAS_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_ARMA4 FOREIGN KEY(FK_ARMA4) REFERENCES DIM_ARMA(ARMAS_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_ATAQUE FOREIGN KEY(FK_ATAQUE) REFERENCES DIM_ATAQUE(ATAQUE_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_OBJ1 FOREIGN KEY(FK_OBJ1) REFERENCES DIM_OBJETIVOS(OBJETIVO_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_OBJ2 FOREIGN KEY(FK_OBJ2) REFERENCES DIM_OBJETIVOS(OBJETIVO_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_OBJ3 FOREIGN KEY(FK_OBJ3) REFERENCES DIM_OBJETIVOS(OBJETIVO_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_IMPACTO FOREIGN KEY(FK_IMPACTO) REFERENCES DIM_IMPACTO(IMPACTO_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_PERPG FOREIGN KEY(FK_PERPG) REFERENCES DIM_GPERP(GRUPO_SK) RELY DISABLE NOVALIDATE;

-- Bitmap Indexes on FK columns
CREATE BITMAP INDEX FACT_FK_TIEMPO_BM ON FACT_GTD_EVENT(FK_TIEMPO_INI);
CREATE BITMAP INDEX FACT_FK_LUGAR_BM ON FACT_GTD_EVENT(FK_LUGAR);
CREATE BITMAP INDEX FACT_FK_ATAQUE_BM ON FACT_GTD_EVENT(FK_ATAQUE);
CREATE BITMAP INDEX FACT_FK_OBJ1_BM ON FACT_GTD_EVENT(FK_OBJ1);
CREATE BITMAP INDEX FACT_FK_IMPACTO_BM ON FACT_GTD_EVENT(FK_IMPACTO);
CREATE BITMAP INDEX FACT_FK_PERPG_BM ON FACT_GTD_EVENT(FK_PERPG);
CREATE BITMAP INDEX FACT_FK_ARMA1_BM ON FACT_GTD_EVENT(FK_ARMA1);
CREATE BITMAP INDEX FACT_FK_DETALLE_BM ON FACT_GTD_EVENT(FK_DETALLE);
CREATE BITMAP INDEX FACT_FK_ESPEC_LUGAR_BM ON FACT_GTD_EVENT(FK_ESPEC_LUGAR);

-- Enable FKs (novalidate - data already loaded)
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_TIEMPO ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_LUGAR ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_ATAQUE ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_OBJ1 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_IMPACTO ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_ESPEC_LUGAR ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_DETALLE ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_DETALLES_A ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_ARMA1 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_ARMA2 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_ARMA3 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_ARMA4 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_OBJ2 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_OBJ3 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_PERPG ENABLE NOVALIDATE;
