-- ============================================================
-- GTD Data Warehouse - Post-ETL Constraints and Indexes
-- Run after FACT_GTD_EVENT is loaded
--
-- Version idempotente: elimina constraints/indexes previos
-- antes de recrearlos, y verifica duplicados/nulls en SKs.
-- ============================================================

SET ECHO ON
SET SERVEROUTPUT ON

-- ------------------------------------------------------------
-- 0. Verificaciones previas: duplicados y nulls en SKs
-- ------------------------------------------------------------
DECLARE
  v_count NUMBER;
BEGIN
  -- Verifica duplicados en cada dimension
  FOR r IN (
    SELECT 'DIM_LUGAR' AS tabla, 'LUGAR_SK' AS sk FROM DUAL UNION ALL
    SELECT 'DIM_DETALLE', 'DETALLE_SK' FROM DUAL UNION ALL
    SELECT 'DIM_ESPEC_LUGAR', 'SPEC_LUGAR_SK' FROM DUAL UNION ALL
    SELECT 'DIM_DETALLES_A', 'DETALLES_A_SK' FROM DUAL UNION ALL
    SELECT 'DIM_ARMA', 'ARMAS_SK' FROM DUAL UNION ALL
    SELECT 'DIM_ATAQUE', 'ATAQUE_SK' FROM DUAL UNION ALL
    SELECT 'DIM_PERPETRADORES', 'PERP_SK' FROM DUAL UNION ALL
    SELECT 'DIM_MCR', 'MCR_SK' FROM DUAL UNION ALL
    SELECT 'DIM_OBJETIVOS', 'OBJETIVO_SK' FROM DUAL UNION ALL
    SELECT 'DIM_IMPACTO', 'IMPACTO_SK' FROM DUAL UNION ALL
    SELECT 'DIM_GPERP', 'GRUPO_SK' FROM DUAL
  ) LOOP
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM (SELECT 1 FROM ' || r.tabla ||
      ' GROUP BY ' || r.sk || ' HAVING COUNT(*) > 1)' INTO v_count;
    IF v_count > 0 THEN
      RAISE_APPLICATION_ERROR(-20001,
        'La tabla ' || r.tabla || ' tiene ' || v_count ||
        ' valores duplicados en ' || r.sk ||
        '. Limpia los duplicados antes de crear PRIMARY KEY.');
    END IF;
  END LOOP;

  -- Verifica nulls en SKs
  FOR r IN (
    SELECT 'DIM_LUGAR' AS tabla, 'LUGAR_SK' AS sk FROM DUAL UNION ALL
    SELECT 'DIM_DETALLE', 'DETALLE_SK' FROM DUAL UNION ALL
    SELECT 'DIM_ESPEC_LUGAR', 'SPEC_LUGAR_SK' FROM DUAL UNION ALL
    SELECT 'DIM_DETALLES_A', 'DETALLES_A_SK' FROM DUAL UNION ALL
    SELECT 'DIM_ARMA', 'ARMAS_SK' FROM DUAL UNION ALL
    SELECT 'DIM_ATAQUE', 'ATAQUE_SK' FROM DUAL UNION ALL
    SELECT 'DIM_PERPETRADORES', 'PERP_SK' FROM DUAL UNION ALL
    SELECT 'DIM_MCR', 'MCR_SK' FROM DUAL UNION ALL
    SELECT 'DIM_OBJETIVOS', 'OBJETIVO_SK' FROM DUAL UNION ALL
    SELECT 'DIM_IMPACTO', 'IMPACTO_SK' FROM DUAL UNION ALL
    SELECT 'DIM_GPERP', 'GRUPO_SK' FROM DUAL
  ) LOOP
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || r.tabla ||
      ' WHERE ' || r.sk || ' IS NULL' INTO v_count;
    IF v_count > 0 THEN
      RAISE_APPLICATION_ERROR(-20002,
        'La tabla ' || r.tabla || ' tiene ' || v_count ||
        ' valores NULL en ' || r.sk ||
        '. Corrige los nulos antes de crear PRIMARY KEY.');
    END IF;
  END LOOP;
END;
/

-- ------------------------------------------------------------
-- 1. Eliminar constraints e indexes existentes (idempotente)
-- ------------------------------------------------------------
BEGIN
  -- Primary keys
  FOR c IN (
    SELECT table_name, constraint_name FROM user_constraints
    WHERE constraint_type = 'P'
      AND constraint_name IN (
        'DIM_LUGAR_PK','DIM_DETALLE_PK','DIM_ESPEC_LUGAR_PK',
        'DIM_DETALLES_A_PK','DIM_ARMA_PK','DIM_ATAQUE_PK',
        'DIM_PERPETRADORES_PK','DIM_MCR_PK','DIM_OBJETIVOS_PK',
        'DIM_IMPACTO_PK','DIM_GPERP_PK'
      )
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE ' || c.table_name || ' DROP CONSTRAINT ' || c.constraint_name;
  END LOOP;

  -- Foreign keys
  FOR c IN (
    SELECT table_name, constraint_name FROM user_constraints
    WHERE constraint_type = 'R'
      AND constraint_name LIKE 'FK_FACT_%'
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE ' || c.table_name || ' DROP CONSTRAINT ' || c.constraint_name;
  END LOOP;

  -- Bitmap indexes
  FOR i IN (
    SELECT index_name FROM user_indexes
    WHERE index_name IN (
      'FACT_FK_FECHA_INI_BM','FACT_FK_FECHA_RES_BM','FACT_FK_LUGAR_BM',
      'FACT_FK_ATAQUE_BM','FACT_FK_OBJ1_BM','FACT_FK_IMPACTO_BM',
      'FACT_FK_PERPG_BM','FACT_FK_ARMA1_BM','FACT_FK_DETALLES_BM',
      'FACT_FK_LUGAR_SPEC_BM'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP INDEX ' || i.index_name;
  END LOOP;
END;
/

-- ------------------------------------------------------------
-- 2. Primary Keys (rely)
-- ------------------------------------------------------------
ALTER TABLE DIM_LUGAR ADD CONSTRAINT DIM_LUGAR_PK PRIMARY KEY(LUGAR_SK) RELY;
ALTER TABLE DIM_DETALLE ADD CONSTRAINT DIM_DETALLE_PK PRIMARY KEY(DETALLE_SK) RELY;
ALTER TABLE DIM_ESPEC_LUGAR ADD CONSTRAINT DIM_ESPEC_LUGAR_PK PRIMARY KEY(SPEC_LUGAR_SK) RELY;
ALTER TABLE DIM_DETALLES_A ADD CONSTRAINT DIM_DETALLES_A_PK PRIMARY KEY(DETALLES_A_SK) RELY;
ALTER TABLE DIM_ARMA ADD CONSTRAINT DIM_ARMA_PK PRIMARY KEY(ARMAS_SK) RELY;
ALTER TABLE DIM_ATAQUE ADD CONSTRAINT DIM_ATAQUE_PK PRIMARY KEY(ATAQUE_SK) RELY;
ALTER TABLE DIM_PERPETRADORES ADD CONSTRAINT DIM_PERPETRADORES_PK PRIMARY KEY(PERP_SK) RELY;
ALTER TABLE DIM_MCR ADD CONSTRAINT DIM_MCR_PK PRIMARY KEY(MCR_SK) RELY;
ALTER TABLE DIM_OBJETIVOS ADD CONSTRAINT DIM_OBJETIVOS_PK PRIMARY KEY(OBJETIVO_SK) RELY;
ALTER TABLE DIM_IMPACTO ADD CONSTRAINT DIM_IMPACTO_PK PRIMARY KEY(IMPACTO_SK) RELY;
ALTER TABLE DIM_GPERP ADD CONSTRAINT DIM_GPERP_PK PRIMARY KEY(GRUPO_SK) RELY;

-- ------------------------------------------------------------
-- 3. Foreign Keys (rely disable novalidate)
-- ------------------------------------------------------------
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_FECHA_INI FOREIGN KEY(FK_FECHA_INI) REFERENCES DIM_TIEMPO(TIEMPO_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_FECHA_RES FOREIGN KEY(FK_FECHA_RES) REFERENCES DIM_TIEMPO(TIEMPO_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_LUGAR FOREIGN KEY(FK_LUGAR) REFERENCES DIM_LUGAR(LUGAR_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_LUGAR_SPEC FOREIGN KEY(FK_LUGAR_SPEC) REFERENCES DIM_ESPEC_LUGAR(SPEC_LUGAR_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_DETALLES FOREIGN KEY(FK_DETALLES) REFERENCES DIM_DETALLE(DETALLE_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_DETALLES_ADICIONALES FOREIGN KEY(FK_DETALLES_ADICIONALES) REFERENCES DIM_DETALLES_A(DETALLES_A_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_ARMA1 FOREIGN KEY(FK_ARMA1) REFERENCES DIM_ARMA(ARMAS_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_ARMA2 FOREIGN KEY(FK_ARMA2) REFERENCES DIM_ARMA(ARMAS_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_ARMA3 FOREIGN KEY(FK_ARMA3) REFERENCES DIM_ARMA(ARMAS_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_ARMA4 FOREIGN KEY(FK_ARMA4) REFERENCES DIM_ARMA(ARMAS_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_ATAQUE FOREIGN KEY(FK_ATAQUE) REFERENCES DIM_ATAQUE(ATAQUE_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_OBJ1 FOREIGN KEY(FK_OBJ1) REFERENCES DIM_OBJETIVOS(OBJETIVO_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_OBJ2 FOREIGN KEY(FK_OBJ2) REFERENCES DIM_OBJETIVOS(OBJETIVO_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_OBJ3 FOREIGN KEY(FK_OBJ3) REFERENCES DIM_OBJETIVOS(OBJETIVO_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_IMPACTO FOREIGN KEY(FK_IMPACTO) REFERENCES DIM_IMPACTO(IMPACTO_SK) RELY DISABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT ADD CONSTRAINT FK_FACT_PERPG FOREIGN KEY(FK_PERPG) REFERENCES DIM_GPERP(GRUPO_SK) RELY DISABLE NOVALIDATE;

-- ------------------------------------------------------------
-- 4. Bitmap Indexes on FK columns
-- ------------------------------------------------------------
CREATE BITMAP INDEX FACT_FK_FECHA_INI_BM ON FACT_GTD_EVENT(FK_FECHA_INI);
CREATE BITMAP INDEX FACT_FK_FECHA_RES_BM ON FACT_GTD_EVENT(FK_FECHA_RES);
CREATE BITMAP INDEX FACT_FK_LUGAR_BM ON FACT_GTD_EVENT(FK_LUGAR);
CREATE BITMAP INDEX FACT_FK_ATAQUE_BM ON FACT_GTD_EVENT(FK_ATAQUE);
CREATE BITMAP INDEX FACT_FK_OBJ1_BM ON FACT_GTD_EVENT(FK_OBJ1);
CREATE BITMAP INDEX FACT_FK_IMPACTO_BM ON FACT_GTD_EVENT(FK_IMPACTO);
CREATE BITMAP INDEX FACT_FK_PERPG_BM ON FACT_GTD_EVENT(FK_PERPG);
CREATE BITMAP INDEX FACT_FK_ARMA1_BM ON FACT_GTD_EVENT(FK_ARMA1);
CREATE BITMAP INDEX FACT_FK_DETALLES_BM ON FACT_GTD_EVENT(FK_DETALLES);
CREATE BITMAP INDEX FACT_FK_LUGAR_SPEC_BM ON FACT_GTD_EVENT(FK_LUGAR_SPEC);

-- ------------------------------------------------------------
-- 5. Enable FKs (novalidate - data already loaded)
-- ------------------------------------------------------------
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_FECHA_INI ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_FECHA_RES ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_LUGAR ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_ATAQUE ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_OBJ1 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_IMPACTO ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_LUGAR_SPEC ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_DETALLES ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_DETALLES_ADICIONALES ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_ARMA1 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_ARMA2 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_ARMA3 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_ARMA4 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_OBJ2 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_OBJ3 ENABLE NOVALIDATE;
ALTER TABLE FACT_GTD_EVENT MODIFY CONSTRAINT FK_FACT_PERPG ENABLE NOVALIDATE;

COMMIT;
