-- ============================================================
-- GTD Data Warehouse - Verification Queries
-- Run after ETL completion
-- ============================================================

-- 1. Row counts for all tables
SELECT 'GTD' AS TABLA, COUNT(*) AS FILAS FROM GTD
UNION ALL SELECT 'DIM_TIEMPO', COUNT(*) FROM DIM_TIEMPO
UNION ALL SELECT 'DIM_LUGAR', COUNT(*) FROM DIM_LUGAR
UNION ALL SELECT 'DIM_DETALLE', COUNT(*) FROM DIM_DETALLE
UNION ALL SELECT 'DIM_ESPEC_LUGAR', COUNT(*) FROM DIM_ESPEC_LUGAR
UNION ALL SELECT 'DIM_DETALLES_A', COUNT(*) FROM DIM_DETALLES_A
UNION ALL SELECT 'DIM_ARMA', COUNT(*) FROM DIM_ARMA
UNION ALL SELECT 'DIM_ATAQUE', COUNT(*) FROM DIM_ATAQUE
UNION ALL SELECT 'DIM_PERPETRADORES', COUNT(*) FROM DIM_PERPETRADORES
UNION ALL SELECT 'DIM_MCR', COUNT(*) FROM DIM_MCR
UNION ALL SELECT 'DIM_OBJETIVOS', COUNT(*) FROM DIM_OBJETIVOS
UNION ALL SELECT 'DIM_IMPACTO', COUNT(*) FROM DIM_IMPACTO
UNION ALL SELECT 'DIM_GPERP', COUNT(*) FROM DIM_GPERP
UNION ALL SELECT 'DIM_BT_GRUPO', COUNT(*) FROM DIM_BT_GRUPO
UNION ALL SELECT 'FACT_GTD_EVENT', COUNT(*) FROM FACT_GTD_EVENT;

-- 2. Ranking de anos por cantidad de atentados
SELECT RANK() OVER (ORDER BY COUNT(*) DESC) AS RANKING,
       IYEAR, COUNT(*) AS CANTIDAD_ATENTADOS
FROM FACT_GTD_EVENT
JOIN DIM_TIEMPO ON (FK_FECHA_INI = TIEMPO_SK)
GROUP BY IYEAR
ORDER BY RANKING;

-- 3. Ataques por pais y tipo de ataque
SELECT COUNTRY_TXT, ATTACKTYPE1_TXT, COUNT(*) AS CANTIDAD
FROM FACT_GTD_EVENT
JOIN DIM_LUGAR ON (FK_LUGAR = LUGAR_SK)
JOIN DIM_ATAQUE ON (FK_ATAQUE = ATAQUE_SK)
GROUP BY COUNTRY_TXT, ATTACKTYPE1_TXT
ORDER BY CANTIDAD DESC;

-- 4. Porcentaje de ataques suicidas
SELECT
    CASE WHEN SUICIDE = 1 THEN 'Si' ELSE 'No' END AS SUICIDIO,
    COUNT(*) AS CANTIDAD,
    ROUND((COUNT(*) / (SELECT COUNT(*) FROM FACT_GTD_EVENT)) * 100, 2) AS PORCENTAJE
FROM FACT_GTD_EVENT
JOIN DIM_ATAQUE ON (FK_ATAQUE = ATAQUE_SK)
GROUP BY SUICIDE;

-- 5. Top 10 grupos perpetradores con ataques suicidas
SELECT GNAME, COUNT(*) AS CANTIDAD
FROM FACT_GTD_EVENT
JOIN DIM_ATAQUE ON (FK_ATAQUE = ATAQUE_SK)
JOIN DIM_GPERP ON (FK_PERPG = GRUPO_SK)
JOIN DIM_BT_GRUPO ON (GRUPO_SK = GRUPO_FK)
JOIN DIM_PERPETRADORES ON (PERP_FK = PERP_SK)
WHERE SUICIDE = 1
GROUP BY GNAME
ORDER BY CANTIDAD DESC
FETCH FIRST 10 ROWS ONLY;

-- 6. Cantidad de ataques por region, pais, ciudad
SELECT REGION_TXT, COUNTRY_TXT, CITY, COUNT(*) AS CANTIDAD
FROM FACT_GTD_EVENT
JOIN DIM_LUGAR ON (FK_LUGAR = LUGAR_SK)
GROUP BY ROLLUP(REGION_TXT, COUNTRY_TXT, CITY)
ORDER BY REGION_TXT, COUNTRY_TXT, CITY;

-- 7. Tipos de arma mas usados
SELECT WEAPTYPE_TXT, COUNT(*) AS CANTIDAD
FROM FACT_GTD_EVENT
JOIN DIM_ARMA ON (FK_ARMA1 = ARMAS_SK)
GROUP BY WEAPTYPE_TXT
ORDER BY CANTIDAD DESC;

-- 8. Total de victimas (muertos + heridos) por ano
SELECT IYEAR,
       SUM(NVL(NKILL, 0) + NVL(NKILLTER, 0)) AS TOTAL_MUERTOS,
       SUM(NVL(NWOUND, 0) + NVL(NWOUNDTE, 0)) AS TOTAL_HERIDOS
FROM FACT_GTD_EVENT
JOIN DIM_TIEMPO ON (FK_FECHA_INI = TIEMPO_SK)
GROUP BY IYEAR
ORDER BY IYEAR;
